"""HTTP transport layer for the Prefab dashboard.

Two routes only:
  GET /        — serves the Prefab-generated HTML page (cached, rebuilt on each
                 new search so the initial state is always fresh)
  GET /api/data — returns the enriched comparison JSON; called every 3 s by the
                 SetInterval + Fetch action baked into the HTML page

The browser page stays open indefinitely.  When the MCP tool writes new data to
current_comparison.json, the next /api/data poll picks it up and the React
runtime updates the cards in-place — no page reload required.
"""

import json
import threading
import time
import webbrowser
from datetime import datetime
from pathlib import Path

from dotenv import load_dotenv
from flask import Flask, jsonify

from prefab_app import _enrich, build_html

load_dotenv()

PREFAB_PORT = 5175
UI_DIR = Path(__file__).parent / "ui"
DATA_FILE = UI_DIR / "current_comparison.json"

flask_app = Flask(__name__)
_server_started = False
_server_lock = threading.Lock()

# Cached HTML — regenerated each time push_comparison_dashboard() is called.
# Serving it from a module-level ref avoids rebuilding on every browser request.
_cached_html: str = ""


# ---------------------------------------------------------------------------
# Flask routes
# ---------------------------------------------------------------------------

@flask_app.route("/")
def serve_dashboard() -> str:
    return _cached_html or "<p>No comparison loaded yet.</p>"


@flask_app.route("/api/data")
def api_data():
    """Live endpoint polled every 3 s by the browser's SetInterval + Fetch."""
    if DATA_FILE.exists():
        try:
            raw = json.loads(DATA_FILE.read_text(encoding="utf-8"))
            return jsonify(_enrich(raw))
        except (json.JSONDecodeError, OSError):
            pass
    return jsonify({"product_name": "", "comparison_data": [], "timestamp": ""})


# ---------------------------------------------------------------------------
# Server lifecycle
# ---------------------------------------------------------------------------

def _is_server_running() -> bool:
    from urllib.request import urlopen
    from urllib.error import URLError
    try:
        urlopen(f"http://127.0.0.1:{PREFAB_PORT}/", timeout=2)
        return True
    except URLError:
        return False


def _start_server() -> None:
    global _server_started
    with _server_lock:
        if _server_started:
            return
        if _is_server_running():
            _server_started = True
            return
        t = threading.Thread(
            target=lambda: flask_app.run(
                port=PREFAB_PORT, debug=False, use_reloader=False
            )
        )
        t.daemon = True
        t.start()
        time.sleep(1)
        _server_started = True


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def push_comparison_dashboard(product_name: str, comparison_data: list[dict]) -> dict:
    """Write comparison data, rebuild the Prefab HTML, start the server, open browser."""
    global _cached_html

    # 1. Persist raw data — /api/data will enrich it on every poll
    UI_DIR.mkdir(parents=True, exist_ok=True)
    payload = {
        "product_name": product_name,
        "comparison_data": comparison_data,
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    }
    DATA_FILE.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    # 2. Rebuild the cached HTML with fresh initial state so a new browser tab
    #    shows the latest data immediately rather than waiting for the first poll
    _cached_html = build_html(_enrich(payload))

    # 3. Start the server (no-op if already running)
    _start_server()

    url = f"http://127.0.0.1:{PREFAB_PORT}/"
    webbrowser.open(url)
    return {
        "status": "success",
        "dashboard_url": url,
        "card_count": len(comparison_data),
        "message": (
            f"Prefab dashboard opened at {url} with {len(comparison_data)} "
            "retailer cards — updates live every 3 s"
        ),
    }


def push_custom_html(product_name: str, html: str) -> dict:
    """Serve a pre-built HTML page generated by the LLM directly.

    This bypasses the static build_html() in prefab_app.py and lets the
    agent inject fully LLM-generated prefab_ui layouts at runtime.
    """
    global _cached_html

    _cached_html = html
    _start_server()

    url = f"http://127.0.0.1:{PREFAB_PORT}/"
    webbrowser.open(url)
    return {
        "status": "success",
        "dashboard_url": url,
        "message": f"LLM-generated dashboard for '{product_name}' opened at {url}",
    }
